apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv-eta-dev
  labels:
    type: local
spec:
  storageClassName: database-eta-dev
  capacity:
    storage: 3Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/var/lib/mysql/eta-dev"
