apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc-eta-dev
  namespace: eta-dev
spec:
  storageClassName: database-eta-dev
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
