apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: eta-dev
  labels:
    app: pages
    tier: database
spec:
  ports:
    - port: 3306
  selector:
    app: pages
    tier: database
  type: ClusterIP
