apiVersion: v1
kind: Service
metadata:
  labels:
    app: pages
    tier: service
  name: pages
  namespace: eta-dev
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: pages
    tier: service
  type: NodePort
